# Application configuration for the Order Service
server:
  port: 8080
  servlet:
    context-path: /api
# db  configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 600000
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect